# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gnn-rblibs}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tarao"]
  s.date = %q{2010-05-07}
  s.description = %q{Some Ruby tweaks for file operations, commandline parsers, etc.}
  s.email = %q{tarao.gnn@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "gnn-rblibs.gemspec",
     "lib/dir/each_leaf.rb",
     "lib/file/kind.rb",
     "lib/file/observer.rb",
     "lib/fileutils/sync.rb",
     "lib/getopt.rb",
     "lib/loadconf.rb",
     "lib/plugin.rb",
     "lib/process/invoke.rb",
     "lib/rbconfig/command.rb",
     "lib/string/random.rb",
     "lib/term/countdown.rb",
     "lib/webrick/single_thread_server.rb",
     "lib/www/mechanize/get.rb",
     "spec/getopt_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tarao/gnn-rblibs}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Some Ruby tweaks}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/getopt_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

